export interface SeedItem {
  externalId: string;
  title: string;
  author: string;
  url: string;
  points: number;
  numComments: number;
  daysAgo: number;
  type: "story" | "comment";
  text: string;
}

export const SEED_ITEMS: SeedItem[] = [
  {
    externalId: "seed-001",
    title: "Show HN: Local-first SQLite sync for indie apps",
    author: "sqlite_fan",
    url: "https://news.ycombinator.com/item?id=seed001",
    points: 412,
    numComments: 89,
    daysAgo: 1,
    type: "story",
    text: "We built a local-first sync layer on top of SQLite with CRDT-inspired conflict resolution. Indie devs can ship offline-capable apps without running Postgres on day one. Early users love not paying per-seat SaaS fees for sync infrastructure.",
  },
  {
    externalId: "seed-002",
    title: "Ask HN: Best self-hosted alternative to Datadog in 2026?",
    author: "ops_lead",
    url: "https://news.ycombinator.com/item?id=seed002",
    points: 287,
    numComments: 156,
    daysAgo: 2,
    type: "story",
    text: "Our observability bill crossed $4k/month for a 12-person team. Looking for self-hosted options that support OpenTelemetry, decent dashboards, and alert routing. Grafana stack feels heavy — what are people actually running in production?",
  },
  {
    externalId: "seed-003",
    title: "Show HN: MCP server that wraps your Postgres schema",
    author: "pgwizard",
    url: "https://news.ycombinator.com/item?id=seed003",
    points: 531,
    numComments: 112,
    daysAgo: 1,
    type: "story",
    text: "We open-sourced an MCP server that exposes Postgres metadata and safe read-only queries to AI coding agents. Cursor and Claude can explore schema without you pasting DDL into every prompt. pgvector support included for RAG prototypes.",
  },
  {
    externalId: "seed-004",
    title: "Comment on AI coding assistant pricing",
    author: "frugaldev",
    url: "https://news.ycombinator.com/item?id=seed004",
    points: 0,
    numComments: 0,
    daysAgo: 3,
    type: "comment",
    text: "The seat-based pricing for AI coding tools is getting ridiculous. Our team of 8 would pay more for Copilot seats than our entire CI budget. We're evaluating local LLMs + Continue.dev but the setup tax is real.",
  },
  {
    externalId: "seed-005",
    title: "Show HN: Open-source Stripe billing UI for SaaS founders",
    author: "indie_saas",
    url: "https://news.ycombinator.com/item?id=seed005",
    points: 198,
    numComments: 44,
    daysAgo: 4,
    type: "story",
    text: "Drop-in React components for Stripe Customer Portal flows with usage-based pricing templates. MIT licensed. Built because every SaaS founder rebuilds the same pricing page and upgrade modal.",
  },
  {
    externalId: "seed-006",
    title: "Postgres vs SQLite for production — heated thread",
    author: "db_skeptic",
    url: "https://news.ycombinator.com/item?id=seed006",
    points: 0,
    numComments: 0,
    daysAgo: 2,
    type: "comment",
    text: "I keep seeing Show HN launches claiming SQLite is production-ready at scale. For read-heavy indie apps, sure. But the moment you need concurrent writes, replication, or row-level security, Postgres still wins. The 'Postgres is overkill' meme is oversold.",
  },
  {
    externalId: "seed-007",
    title: "Show HN: Self-hosted feature flags with GitOps sync",
    author: "flagops",
    url: "https://news.ycombinator.com/item?id=seed007",
    points: 156,
    numComments: 37,
    daysAgo: 5,
    type: "story",
    text: "Feature flags stored in Git, synced to edge nodes. No SaaS pricing, no SDK phone-home. Docker Compose one-liner for homelab and production k8s manifests included.",
  },
  {
    externalId: "seed-008",
    title: "Ask HN: How do you evaluate AI coding tools for your team?",
    author: "eng_mgr",
    url: "https://news.ycombinator.com/item?id=seed008",
    points: 342,
    numComments: 201,
    daysAgo: 3,
    type: "story",
    text: "We're piloting Cursor, Copilot, and a self-hosted Continue setup. Criteria: privacy, context window quality, MCP integration, and total cost at 25 seats. Would love to hear how other teams ran bake-offs without turning it into a religious war.",
  },
  {
    externalId: "seed-009",
    title: "Comment on vendor lock-in fears",
    author: "cloud_exit",
    url: "https://news.ycombinator.com/item?id=seed009",
    points: 0,
    numComments: 0,
    daysAgo: 6,
    type: "comment",
    text: "Every AI devtool wants your repo context in their cloud. Export paths are immature. We're standardizing on MCP so we can swap agents without re-ingesting embeddings into five different vector DBs.",
  },
  {
    externalId: "seed-010",
    title: "Show HN: pgvector-powered doc search for internal wikis",
    author: "vector_fan",
    url: "https://news.ycombinator.com/item?id=seed010",
    points: 267,
    numComments: 58,
    daysAgo: 2,
    type: "story",
    text: "Self-hosted RAG over Confluence/Notion exports using Postgres + pgvector. No Pinecone bill. Chunking tuned for engineering docs. AGPL — happy to hear feedback from teams running similar stacks.",
  },
  {
    externalId: "seed-011",
    title: "SaaS pricing transparency thread",
    author: "buyer_advocate",
    url: "https://news.ycombinator.com/item?id=seed011",
    points: 0,
    numComments: 0,
    daysAgo: 1,
    type: "comment",
    text: "HN devtools threads this week are full of founders posting pricing pages after getting roasted for 'contact sales' only plans. Transparency wins trust. Seat + usage hybrid models confuse everyone.",
  },
  {
    externalId: "seed-012",
    title: "Show HN: CLI for migrating from Heroku Postgres to Neon",
    author: "migrate_easy",
    url: "https://news.ycombinator.com/item?id=seed012",
    points: 143,
    numComments: 29,
    daysAgo: 5,
    type: "story",
    text: "One-command logical replication setup with progress bars and rollback. Built after helping three indie teams escape Heroku pricing shocks. Supports pgvector extensions if you already enabled them.",
  },
  {
    externalId: "seed-013",
    title: "Ask HN: Is local LLM coding good enough now?",
    author: "privacy_first",
    url: "https://news.ycombinator.com/item?id=seed013",
    points: 489,
    numComments: 312,
    daysAgo: 4,
    type: "story",
    text: "Running Qwen and DeepSeek locally on a Mac Studio. Refactoring is decent; greenfield scaffolding still weaker than GPT-4 class models. For regulated industries though, air-gapped beats API keys. What's your cutoff for 'good enough'?",
  },
  {
    externalId: "seed-014",
    title: "Comment on open source sustainability",
    author: "maintainer",
    url: "https://news.ycombinator.com/item?id=seed014",
    points: 0,
    numComments: 0,
    daysAgo: 3,
    type: "comment",
    text: "Another viral OSS devtool with no business model. HN celebrates the launch, then ignores the maintainer burnout thread six months later. We need more honest conversations about open core vs pure OSS.",
  },
  {
    externalId: "seed-015",
    title: "Show HN: Indie analytics — privacy-first Plausible fork",
    author: "metrics_indie",
    url: "https://news.ycombinator.com/item?id=seed015",
    points: 221,
    numComments: 51,
    daysAgo: 6,
    type: "story",
    text: "Self-hosted web analytics with a simpler UI and flat pricing for bootstrapped founders. No cookie banners required in EU if configured correctly. Docker image under 200MB.",
  },
  {
    externalId: "seed-016",
    title: "Infrastructure cost optimization debate",
    author: "finops_hn",
    url: "https://news.ycombinator.com/item?id=seed016",
    points: 0,
    numComments: 0,
    daysAgo: 2,
    type: "comment",
    text: "Teams migrating from managed Kafka to Redpanda self-hosted report 60% savings but higher ops headcount. The break-even point depends on whether you already have platform engineers.",
  },
  {
    externalId: "seed-017",
    title: "Show HN: Devcontainer templates for AI agent workflows",
    author: "agent_dev",
    url: "https://news.ycombinator.com/item?id=seed017",
    points: 178,
    numComments: 41,
    daysAgo: 1,
    type: "story",
    text: "Preconfigured devcontainers with MCP servers, linters, and test runners so coding agents start from a reproducible environment. Works with Cursor and Claude Code out of the box.",
  },
  {
    externalId: "seed-018",
    title: "Ask HN: Database for multi-tenant SaaS at small scale?",
    author: "saas_starter",
    url: "https://news.ycombinator.com/item?id=seed018",
    points: 256,
    numComments: 134,
    daysAgo: 5,
    type: "story",
    text: "Postgres with schema-per-tenant vs shared schema with row-level security? We're at 40 customers, 3 engineers. Want to avoid a migration cliff at 200 tenants.",
  },
  {
    externalId: "seed-019",
    title: "Comment on AI-generated Show HN spam",
    author: "hn_regular",
    url: "https://news.ycombinator.com/item?id=seed019",
    points: 0,
    numComments: 0,
    daysAgo: 1,
    type: "comment",
    text: "Too many Show HN posts this week read like ChatGPT marketing copy. The community pushes back hard when demos are vaporware or landing pages without working OSS repos.",
  },
  {
    externalId: "seed-020",
    title: "Show HN: Terraform modules for homelab k8s",
    author: "homelab_k8s",
    url: "https://news.ycombinator.com/item?id=seed020",
    points: 134,
    numComments: 27,
    daysAgo: 7,
    type: "story",
    text: "Opinionated Terraform + Talos Linux modules for a production-like homelab. Includes observability stack and secrets management patterns borrowed from day-job infra teams.",
  },
  {
    externalId: "seed-021",
    title: "Cursor vs Copilot workflow comparison",
    author: "daily_driver",
    url: "https://news.ycombinator.com/item?id=seed021",
    points: 0,
    numComments: 0,
    daysAgo: 2,
    type: "comment",
    text: "Cursor wins on multi-file edits and MCP tool use. Copilot wins on inline completion latency in VS Code. Neither handles monorepo context perfectly — both benefit from a good AGENTS.md file.",
  },
  {
    externalId: "seed-022",
    title: "Show HN: Billing alerts before your cloud bill surprises you",
    author: "cloud_bill",
    url: "https://news.ycombinator.com/item?id=seed022",
    points: 167,
    numComments: 33,
    daysAgo: 4,
    type: "story",
    text: "Open-source AWS/GCP cost anomaly detector with Slack alerts. Built after an idle RDS instance cost us $800. Self-hostable, reads billing exports — no third-party cloud access.",
  },
  {
    externalId: "seed-023",
    title: "Ask HN: Best practices for pgvector at scale?",
    author: "rag_builder",
    url: "https://news.ycombinator.com/item?id=seed023",
    points: 198,
    numComments: 87,
    daysAgo: 3,
    type: "story",
    text: "IVFFlat vs HNSW indexing tradeoffs, reindexing strategies, and when to move to a dedicated vector DB. We're at 2M chunks in Postgres and latency is creeping up on hybrid search queries.",
  },
  {
    externalId: "seed-024",
    title: "Comment on indie product launch fatigue",
    author: "builder_fatigue",
    url: "https://news.ycombinator.com/item?id=seed024",
    points: 0,
    numComments: 0,
    daysAgo: 5,
    type: "comment",
    text: "Show HN volume is up but front-page diversity feels down — lots of AI wrappers with similar positioning. The posts that break through have live demos, honest limitations, and responsive founders in comments.",
  },
  {
    externalId: "seed-025",
    title: "Show HN: Git-native CMS for developer docs",
    author: "docs_dev",
    url: "https://news.ycombinator.com/item?id=seed025",
    points: 145,
    numComments: 36,
    daysAgo: 6,
    type: "story",
    text: "Markdown in Git, preview deployments on PRs, full-text search via Postgres. Alternative to Notion for teams that want docs-as-code without building a static site pipeline from scratch.",
  },
  {
    externalId: "seed-026",
    title: "Self-hosting email infra pain points",
    author: "mail_ops",
    url: "https://news.ycombinator.com/item?id=seed026",
    points: 0,
    numComments: 0,
    daysAgo: 4,
    type: "comment",
    text: "Every self-hosting thread eventually hits email deliverability. Devtools founders underestimate SPF/DKIM/DMARC setup when moving off SendGrid. This week's Ask HN had three teams bitten by it.",
  },
  {
    externalId: "seed-027",
    title: "Show HN: Type-safe RPC layer for full-stack TS teams",
    author: "typesafe_fan",
    url: "https://news.ycombinator.com/item?id=seed027",
    points: 189,
    numComments: 48,
    daysAgo: 2,
    type: "story",
    text: "End-to-end typed API contracts with OpenAPI export and client generation. Aims to reduce the tRPC vs REST debate by supporting both from one schema. MIT licensed.",
  },
  {
    externalId: "seed-028",
    title: "Open source license drama on HN",
    author: "license_watcher",
    url: "https://news.ycombinator.com/item?id=seed028",
    points: 0,
    numComments: 0,
    daysAgo: 3,
    type: "comment",
    text: "Another popular devtool switched from MIT to BSL this week. HN comments split between supporting sustainable OSS and accusing bait-and-switch. Expect more license threads next week.",
  },
  {
    externalId: "seed-029",
    title: "Show HN: Minimal CI runner you can self-host on a NUC",
    author: "ci_minimal",
    url: "https://news.ycombinator.com/item?id=seed029",
    points: 112,
    numComments: 24,
    daysAgo: 7,
    type: "story",
    text: "GitHub Actions compatible runner in a single Go binary. For indie teams tired of minute-based pricing on hosted CI. Supports Docker-in-Docker with sane defaults.",
  },
  {
    externalId: "seed-030",
    title: "Ask HN: How are you using MCP in production?",
    author: "mcp_curiosity",
    url: "https://news.ycombinator.com/item?id=seed030",
    points: 378,
    numComments: 167,
    daysAgo: 1,
    type: "story",
    text: "MCP hype is real on HN this week. Teams connecting internal APIs, databases, and ticketing systems to coding agents. Security concerns about overly permissive tool access keep coming up in comments.",
  },
  {
    externalId: "seed-031",
    title: "Comment on database migration horror stories",
    author: "migration_scar",
    url: "https://news.ycombinator.com/item?id=seed031",
    points: 0,
    numComments: 0,
    daysAgo: 2,
    type: "comment",
    text: "Zero-downtime migrations are easy in conference talks, hard in legacy schemas. This week's Postgres threads recommend expand-contract patterns and feature flags for dual-write phases.",
  },
  {
    externalId: "seed-032",
    title: "Show HN: Usage-based billing SDK for Stripe + Postgres",
    author: "metered_billing",
    url: "https://news.ycombinator.com/item?id=seed032",
    points: 156,
    numComments: 39,
    daysAgo: 5,
    type: "story",
    text: "Track metered events in Postgres, aggregate nightly, sync to Stripe Billing. Built for API products tired of rolling their own usage pipelines. Includes idempotency and replay tools.",
  },
  {
    externalId: "seed-033",
    title: "AI agent reliability complaints",
    author: "skeptical_eng",
    url: "https://news.ycombinator.com/item?id=seed033",
    points: 0,
    numComments: 0,
    daysAgo: 1,
    type: "comment",
    text: "Agents that confidently apply wrong refactors are this week's top complaint in AI coding threads. Teams adding mandatory human review on PRs opened by agents — treat them like junior devs, not autopilot.",
  },
  {
    externalId: "seed-034",
    title: "Show HN: Edge-deployable WASM plugin system for APIs",
    author: "wasm_edge",
    url: "https://news.ycombinator.com/item?id=seed034",
    points: 201,
    numComments: 45,
    daysAgo: 4,
    type: "story",
    text: "Sandboxed WASM plugins for request/response transforms at the edge. Alternative to Lua in nginx or cloud vendor-specific extensions. Self-host with Fly.io or bare metal.",
  },
  {
    externalId: "seed-035",
    title: "Predictions: next week on HN devtools",
    author: "hn_oracle",
    url: "https://news.ycombinator.com/item?id=seed035",
    points: 0,
    numComments: 0,
    daysAgo: 1,
    type: "comment",
    text: "Expect more MCP server launches, Postgres extension showcases, and Ask HN threads comparing AI coding spend vs hiring a contractor. Self-hosting wins when SaaS prices jump after funding rounds.",
  },
  {
    externalId: "seed-036",
    title: "Show HN: Cron-as-code with Git history and rollbacks",
    author: "cron_git",
    url: "https://news.ycombinator.com/item?id=seed036",
    points: 128,
    numComments: 31,
    daysAgo: 6,
    type: "story",
    text: "Define scheduled jobs in YAML in Git, deploy via CI, audit changes like infrastructure code. Self-hosted agent runs jobs with secrets from Vault. Reaction to opaque SaaS cron products.",
  },
  {
    externalId: "seed-037",
    title: "Developer tools market saturation",
    author: "market_watch",
    url: "https://news.ycombinator.com/item?id=seed037",
    points: 0,
    numComments: 0,
    daysAgo: 3,
    type: "comment",
    text: "HN devtools audience rewards sharp positioning and honest benchmarks. Another vector DB launch without comparison data gets buried. Founders who show migration guides from incumbents do better.",
  },
  {
    externalId: "seed-038",
    title: "Show HN: Local RAG stack in a single Docker Compose file",
    author: "rag_docker",
    url: "https://news.ycombinator.com/item?id=seed038",
    points: 312,
    numComments: 72,
    daysAgo: 2,
    type: "story",
    text: "Postgres + pgvector + embedding worker + Next.js UI — one compose file for demos and small teams. Mock mode when no OpenAI key. Designed for engineering screening projects and internal POCs.",
  },
  {
    externalId: "seed-039",
    title: "Ask HN: When did you switch from Supabase to self-hosted Postgres?",
    author: "supabase_grad",
    url: "https://news.ycombinator.com/item?id=seed039",
    points: 276,
    numComments: 143,
    daysAgo: 5,
    type: "story",
    text: "Love Supabase for speed to market. Curious at what scale or cost point teams migrate to self-managed Postgres. Auth and realtime are the sticky parts — how did you replace them?",
  },
  {
    externalId: "seed-040",
    title: "Comment on documentation as devtool differentiator",
    author: "docs_matter",
    url: "https://news.ycombinator.com/item?id=seed040",
    points: 0,
    numComments: 0,
    daysAgo: 4,
    type: "comment",
    text: "Tools with excellent quickstart docs dominate HN launch threads. Five-minute demos beat feature matrices. Several complaints this week about AI devtools with vague security docs.",
  },
];
