import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatDate(date: Date | string | null | undefined): string {
  if (!date) return "—";
  const d = typeof date === "string" ? new Date(date) : date;
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

export function truncate(text: string, max = 160): string {
  if (text.length <= max) return text;
  return `${text.slice(0, max).trim()}…`;
}

export function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** Canonical Hacker News discussion URL for a story or comment id. */
export function hnDiscussionUrl(externalId: string): string {
  return `https://news.ycombinator.com/item?id=${externalId}`;
}

/** True when a URL points at an HN item/discussion page (not an external link). */
export function isHnDiscussionUrl(url: string): boolean {
  try {
    const { hostname, pathname } = new URL(url);
    return (
      (hostname === "news.ycombinator.com" || hostname === "www.news.ycombinator.com") &&
      pathname === "/item"
    );
  } catch {
    return false;
  }
}

/**
 * Canonical key for matching a cited source title to a stored source title.
 * Strips HTML, lowercases, unifies dash variants (–, —, ‐, etc.) and quotes to
 * ASCII, drops other punctuation, and collapses whitespace — so citation text
 * generated by the model resolves to the right source despite cosmetic
 * differences. Used on BOTH the server (map builder) and client (pill resolver)
 * so keys line up exactly.
 */
export function normalizeSourceTitle(title: string): string {
  return stripHtml(title)
    .toLowerCase()
    .replace(/[\u2010-\u2015\u2212]/g, "-") // dash variants -> hyphen
    .replace(/[\u2018\u2019\u201b\u2032`]/g, "'") // smart single quotes -> '
    .replace(/[\u201c\u201d\u201e\u2033]/g, '"') // smart double quotes -> "
    .replace(/[^a-z0-9]+/g, " ") // drop remaining punctuation
    .replace(/\s+/g, " ")
    .trim();
}

/** Strip HTML tags and decode common entities from HN comment text. */
export function stripHtml(text: string): string {
  if (!text) return "";

  const withoutTags = text.replace(/<[^>]*>/g, " ");

  const decoded = withoutTags
    .replace(/&nbsp;/gi, " ")
    .replace(/&quot;/gi, '"')
    .replace(/&apos;/gi, "'")
    .replace(/&#0?39;/gi, "'")
    .replace(/&lt;/gi, "<")
    .replace(/&gt;/gi, ">")
    .replace(/&amp;/gi, "&")
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex: string) =>
      String.fromCodePoint(parseInt(hex, 16)),
    )
    .replace(/&#(\d+);/g, (_, dec: string) => String.fromCodePoint(parseInt(dec, 10)));

  return decoded.replace(/\s+/g, " ").trim();
}
